language: php
php:
- 5.6
- 7.0
- 7.1
- 7.2
- 7.3

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - composer self-update
  - composer global require "fxp/composer-asset-plugin:*"
  - composer install
  - vendor/bin/codecept build

script: vendor/bin/codecept run